CREATE TABLE IF NOT EXISTS hack_room
(
	ID int(11) AUTO_INCREMENT NOT NULL,
	ARTIST_ID int(11) NOT NULL,
	WORD varchar(255) NOT NULL,
	PICTURE_ID INT(11) NOT NULL,

	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS hack_message
(
	ID int(11) AUTO_INCREMENT NOT NULL,
	ROOM_ID int(11) NOT NULL,
	USER_ID int(11) NOT NULL,
	MESSAGE TEXT NOT NULL,

	PRIMARY KEY (ID),
	FOREIGN KEY (ROOM_ID) REFERENCES hack_room (ID)
);